stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  image: openjdk:21-jdk-slim
  script:
    - cd sample_project/bsn-validator
    - apt-get update
    - apt-get install -y maven
    - mvn clean compile
  artifacts:
    paths:
      - sample_project/bsn-validator/target/

test:
  stage: test
  image: openjdk:21-jdk-slim
  script:
    - cd sample_project/bsn-validator
    - apt-get update
    - apt-get install -y maven
    - mvn test
  artifacts:
    reports:
      junit: sample_project/bsn-validator/target/surefire-reports/TEST-*.xml

package:
  stage: package
  image: openjdk:21-jdk-slim
  script:
    - cd sample_project/bsn-validator
    - apt-get update
    - apt-get install -y maven
    - mvn package
  artifacts:
    paths:
      - sample_project/bsn-validator/target/*.jar

deploy-dev:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd sample_project/bsn-validator
    - docker build -t bsn-validator:latest .
    - docker-compose -f docker-compose.dev.yml up -d
  only:
    - main
  environment:
    name: development

deploy-test:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd sample_project/bsn-validator
    - docker build -t bsn-validator:test .
    - docker-compose -f docker-compose.yml up -d
  only:
    - test
  environment:
    name: test

deploy-acc:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd sample_project/bsn-validator
    - docker build -t bsn-validator:acc .
    - docker-compose -f docker-compose.acc.yml up -d
  only:
    - staging
  environment:
    name: acceptance

deploy-prod:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd sample_project/bsn-validator
    - docker build -t bsn-validator:prod .
    - docker-compose -f docker-compose.prod.yml up -d
  only:
    - tags
  environment:
    name: production
  when: manual